use it_company;

SELECT * FROM EMPLOYEE2;

-- CREATING NEW TABLE FROM NEW TABLE
-- SYNTAX
-- CREATE TABLE NEW_TABLE_NAME AS
-- SELECT * FROM OLD_TABLLE_NAME;
CREATE TABLE EMPLOYEE2_BACKUP AS
SELECT * FROM EMPLOYEE2;

-- SELECTING THE EMPLOYEE2_BACKUP TABLE
SELECT * FROM EMPLOYEE2_BACKUP;

-- OLD ID,DEPT FROM OLD TABLE
CREATE TABLE EMPLOYEE2_BACKUP2 AS
SELECT ID,DEPT FROM EMPLOYEE2;

SELECT * FROM EMPLOYEE2_BACKUP2;

describe EMPLOYEE2_BACKUP;

describe EMPLOYEE2;

-- CREATING NEW TABLE AND SELECTING SOME RECORDS FROM EXISTING TABLE
CREATE TABLE EMPLOYEE2_3 AS
SELECT * FROM EMPLOYEE2
WHERE DEPT='IT';

SELECT * FROM EMPLOYEE2_3;

-- CREATING TABLE BY ONLY COPYING THE STRUCTURE OF PREVIOUS TABLE
CREATE TABLE EMPLOYEE2_4 AS
SELECT * FROM EMPLOYEE2
WHERE 1=0;

SELECT * FROM EMPLOYEE2_4;

-- APPROACH 2 FOR COPYING THE STRUCTURE OF TABLE
CREATE TABLE EMPLOYEE2_5 AS
SELECT * FROM EMPLOYEE2;
 -- TO DELETE RECORDS AND TI MAINTAIN SAME STRUCTURE
TRUNCATE TABLE EMPLOYEE2_5;
SELECT COUNT(*) FROM EMPLOYEE2_5;
SELECT * FROM EMPLOYEE2_5;

-- COMPUTED COLUMN:-A column which is derived from existed column value
-- COMPUTED COLUMN/DERIVED COLUMN
CREATE TABLE ORDERS(
ID INT auto_increment,
PRICE INT UNSIGNED NOT NULL,
QUANTITY INT UNSIGNED NOT NULL,
TOTAL_PRICE INT GENERATED ALWAYS AS (PRICE * QUANTITY) STORED,
PRIMARY KEY(ID)
);


INSERT INTO ORDERS(PRICE,QUANTITY)
values (10,2),(20,3),(30,4);

SELECT * FROM ORDERS;

-- ADDING NEW COLUMNS TO ORDERS TABLE
ALTER TABLE ORDERS 
ADD SUM_TO_NUMBERS INT GENERATED ALWAYS AS (PRICE+QUANTITY) STORED;

-- SUBTRACTION
ALTER TABLE ORDERS 
ADD DIFFERENCE_TO_NUMBERS INT GENERATED ALWAYS AS (PRICE-QUANTITY) STORED;

ALTER TABLE ORDERS 
ADD MULTIPLY_TO_NUMBERS INT GENERATED ALWAYS AS (PRICE*QUANTITY) STORED;

ALTER TABLE ORDERS 
ADD DIVISION_TO_NUMBERS INT GENERATED ALWAYS AS (PRICE/QUANTITY) STORED;

ALTER TABLE ORDERS 
ADD MODULO_TO_NUMBERS INT GENERATED ALWAYS AS (PRICE%QUANTITY) STORED;

SELECT * FROM ORDERS;


