CREATE DATABASE IT_COMPANY;

DROP DATABASE it_company;

CREATE DATABASE IF NOT exists IT_COMPANY;

CREATE DATABASE IF NOT exists NON_IT_COMPANY;

USE IT_COMPANY;

CREATE TABLE EMPLOYEES(EMPID INT,EMPNAME char(20),AGE INT);

SELECT *FROM EMPLOYEES;
-- TO GET TABLE STRUCTURE--
describe EMPLOYEES;

-- ADD NEW COLUMN--
ALTER TABLE EMPLOYEES ADD SALARY INT;
describe EMPLOYEES;
ALTER TABLE EMPLOYEES ADD SALARY2 INT;
ALTER TABLE EMPLOYEES DROP SALARY2 ;
RENAME TABLE EMPLOYEES TO EMP_INFO;
describe EMP_INFO;
ALTER TABLE EMP_INFO
RENAME COLUMN AGE TO EMP_AGE;
DESCRIBE EMP_INFO;
-- MODIFYING THE COLUMN DATA TYPE
ALTER TABLE EMP_INFO 
modify EMPNAME CHAR(50);
describe EMP_INFO; 
ALTER TABLE EMP_INFO 
modify EMPNAME VARCHAR(50);
describe EMP_INFO; 
DROP TABLE EMP_INFO;
DROP database IF exists non_it_company;
SELECT * FROM EMP_INFO;
