CREATE DATABASE DQL_DATABASE;

use DQL_DATABASE;
select * from TIPS;

-- DDL QUERIES
-- CHANGE COLUMN SEX TO GENDER
ALTER TABLE TIPS RENAME COLUMN SEX TO GENDER;

-- DQL QUERIES
-- TIME,SIZE,DAY,TIP
SELECT TIME,SIZE,DAY,TIP FROM TIPS;

-- RECORDS WHERE SMOKER IS YES
SELECT * FROM TIPS 
WHERE SMOKER='YES';

-- RECORDS WHICH ONE  IS SMOKER AND SIZE=3
SELECT * FROM TIPS 
WHERE SIZE=3 AND SMOKER='YES';

-- RECORDS WHICH ARE SIZE IN (2,3,4)
SELECT * FROM TIPS
WHERE SIZE=2 OR SIZE=3 OR SIZE=4;
-- BY USING STRING OPERATOR
SELECT * FROM TIPS
WHERE SIZE IN (2,3,4);

-- TIP BETWEEN 10-20
SELECT * FROM TIPS
WHERE TIP BETWEEN 10 AND 20;
-- OR
SELECT * FROM TIPS
WHERE TIP>=10 AND TIP<=20;

-- DAY IN SAT,SUN,MON AND SMOKER IS YES
SELECT * FROM TIPS 
WHERE DAY IN ('SAT','MON','SUN') AND SMOKER='YES';

-- which are non smoker and gender is male
SELECT * FROM TIPS 
WHERE SMOKER='NO' AND GENDER='MALE';

-- NON SMOKER WITH DINNER TIME
SELECT * FROM TIPS
WHERE SMOKER='NO' AND TIME='DINNER';

-- AVERAGE TOTAL BILL OF NON SMOKER WITH IN THE SIZE NOT IN(2,3,6)
SELECT AVG(TOTAL_BILL) FROM TIPS
WHERE SMOKER='NO' AND SIZE NOT IN (2,3,6);
SELECT * FROM TIPS;

-- COUNT ASS TOTAL RECORDS COUNT,MIN BILL AS MINIMUM BILL,MAX BILL AS MAXIMUM BILL OF SMOKERS WITH SIZE IS 2 OR 3
SELECT COUNT(*) AS "TOTAL RECORDS",
MIN(TOTAL_BILL) AS "MINIMUM BILL",
MAX(TOTAL_BILL) AS "MAXIMUM BILL"
FROM TIPS 
WHERE SMOKER ='YES' AND SIZE=2 OR SIZE=3;


-- SIZE ONLY 2
SELECT COUNT(*) AS "TOTAL RECORDS",
MIN(TOTAL_BILL) AS "MINIMUM BILL",
MAX(TOTAL_BILL) AS "MAXIMUM BILL"
FROM TIPS 
WHERE SIZE=2 ;

-- SIZE ONLY 3
SELECT COUNT(*) AS "TOTAL RECORDS",
MIN(TOTAL_BILL) AS "MINIMUM BILL",
MAX(TOTAL_BILL) AS "MAXIMUM BILL"
FROM TIPS 
WHERE SIZE=3;

SELECT COUNT(*) AS "TOTAL RECORDS",
MIN(TOTAL_BILL) AS "MINIMUM BILL",
MAX(TOTAL_BILL) AS "MAXIMUM BILL"
FROM TIPS 
WHERE SIZE=4;

SELECT COUNT(*) AS "TOTAL RECORDS",
MIN(TOTAL_BILL) AS "MINIMUM BILL",
MAX(TOTAL_BILL) AS "MAXIMUM BILL"
FROM TIPS 
WHERE SIZE=5;


SELECT COUNT(*) AS "TOTAL RECORDS",
MIN(TOTAL_BILL) AS "MINIMUM BILL",
MAX(TOTAL_BILL) AS "MAXIMUM BILL"
FROM TIPS 
WHERE SIZE=6;

SELECT COUNT(*) AS "TOTAL RECORDS",
MIN(TOTAL_BILL) AS "MINIMUM BILL",
MAX(TOTAL_BILL) AS "MAXIMUM BILL"
FROM TIPS 
WHERE SIZE=3 ;

-- USING GROUP BY
-- COUNT TOTAL RECORDS OF EACH GROUP OF SIZE 
SELECT SIZE,COUNT(*) "TOTAL RECORDS"  FROM TIPS
GROUP BY SIZE; 


-- COUNT TOTAL RECORDS OF SMOKER  GROUP
SELECT SMOKER,COUNT(*) "TOTAL REDCORDS" FROM TIPS
GROUP BY SMOKER; 
 
-- TOTAL BILL OF SMOKER
SELECT SMOKER,SUM(TOTAL_BILL) "TOTAL BILL" FROM TIPS
WHERE SMOKER='YES' 
GROUP BY SMOKER;

-- TOTAL BILLS OF GENDER
SELECT GENDER,SUM(TOTAL_BILL) "TOTAL BILL" FROM TIPS
WHERE GENDER='MALE' OR GENDER='FEMALE' 
GROUP BY GENDER;

-- TOTAL BILLS OF GENDER WITH SIZE 2
SELECT GENDER,SUM(TOTAL_BILL) "TOTAL BILL" FROM TIPS
WHERE GENDER='MALE' OR GENDER='FEMALE' AND SIZE=2 
GROUP BY GENDER;