-- SELECT ALL COLUMNS FROM TIPS TABLE
SELECT * FROM TIPS;

-- RECORDS OF SIZE=3 AND GENDER IS FEMALE
SELECT * FROM TIPS
WHERE GENDER='FEMALE' AND SIZE=3;

-- RECORDS WHICH ARE HAVING DINNER TIME AND GENDER IS FEMALE
SELECT * FROM TIPS
WHERE TIME='DINNER' AND GENDER ='FEMALE';

-- RECORDS WHERE GENDER IS MALE AND SIZE IN (2,3,4)
SELECT * FROM TIPS
WHERE GENDER='MALE' AND SIZE IN (2,3,4);
-- OR
SELECT * FROM TIPS
WHERE GENDER ="MALE" AND (SIZE=2 OR SIZE=3 OR SIZE=4);

-- TOTAL BILL IN RANGE 20 TO 30  
SELECT * FROM TIPS
WHERE TOTAL_BILL BETWEEN 20 AND 30;
-- OR
SELECT * FROM TIPS
WHERE TOTAL_BILL>=20 AND TOTAL_BILL<=30;

-- TOTAL RECORDS COUNT OF DAY IN FRIDAY,SAT,SUNDAY WITH DINNER TIME
SELECT TIME,DAY,COUNT(*) FROM TIPS
WHERE TIME='DINNER'
GROUP BY DAY;
-- OR
SELECT DAY,COUNT(*) FROM TIPS
WHERE TIME='DINNER'
GROUP BY DAY;
-- TOTAL RECORDS COUNT OF DAY IS SUN WITH SIZE 3 AND DAY IS SAT WITH SIZE 4
SELECT * FROM TIPS
WHERE (DAY='SUN' AND SIZE=3) OR (DAY='SAT' AND SIZE=4);

-- FETCH THE FOLLOWING DETAILS TO ALL SIZE WITH SPECIFIED ONE
		-- TOTAL BILL AS 'TOTAL BILL OF SIZE 2'
SELECT COUNT(*) AS "TOTAL RECORDS"
FROM TIPS 
WHERE SIZE=2 ;
-- OR
SELECT COUNT(*) AS TOTAL_RECORDS
FROM TIPS 
WHERE SIZE=2 ;
        -- MIN BILL AS 'MINIMUM BILL OF SIZE 2'
        -- MAX BILL AS 'MAXIMUM BILL OF SIZE 2' FOR SIZE 2
SELECT COUNT(*) AS "TOTAL RECORDS OF SIZE 2",
SUM(TOTAL_BILL) AS "TOTAL_BILL OF SIZE 2",
MIN(TOTAL_BILL) AS "MINIMUM BILL OF SIZE 2",
MAX(TOTAL_BILL) AS "MAXIMUM BILL OF SIZE 2"
FROM TIPS 
WHERE SIZE=2;
        -- FOR SIZE 3 MALE SMOKERS
SELECT COUNT(*) AS "TOTAL RECORDS OF SIZE 2",
SUM(TOTAL_BILL) AS "TOTAL_BILL OF SIZE 2",
MIN(TOTAL_BILL) AS "MINIMUM BILL OF SIZE 2",
MAX(TOTAL_BILL) AS "MAXIMUM BILL OF SIZE 2"
FROM TIPS 
WHERE SMOKER ='YES' AND SIZE=3 AND GENDER="MALE";

        -- FOR SIZE 4 NOT IN (SAT,SUN,MON)
SELECT COUNT(*) AS "TOTAL RECORDS ",
SUM(TOTAL_BILL) AS "TOTAL_BILL OF ",
MIN(TOTAL_BILL) AS "MINIMUM BILL ",
MAX(TOTAL_BILL) AS "MAXIMUM BILL "
FROM TIPS 
WHERE SIZE=4 AND DAY NOT IN ('SAT','SUN','MON');
-- OR
SELECT COUNT(*) AS "TOTAL RECORDS ",
SUM(TOTAL_BILL) AS "TOTAL_BILL OF ",
MIN(TOTAL_BILL) AS "MINIMUM BILL ",
MAX(TOTAL_BILL) AS "MAXIMUM BILL "
FROM TIPS 
WHERE SIZE=4 AND (DAY!='SAT' AND DAY!='SUN' AND DAY!='MON');
        -- FOR SIZE 5 MALE NON - SMOKERS
SELECT COUNT(*) AS "TOTAL RECORDS ",
SUM(TOTAL_BILL) AS "TOTAL_BILL OF ",
MIN(TOTAL_BILL) AS "MINIMUM BILL ",
MAX(TOTAL_BILL) AS "MAXIMUM BILL "
FROM TIPS 
WHERE SIZE=5 AND GENDER="MALE" AND SMOKER='NO';
        -- FOR SIZE 6
SELECT COUNT(*) AS "TOTAL RECORDS ",
SUM(TOTAL_BILL) AS "TOTAL_BILL OF ",
MIN(TOTAL_BILL) AS "MINIMUM BILL ",
MAX(TOTAL_BILL) AS "MAXIMUM BILL "
FROM TIPS 
WHERE SIZE=6;

-- FOR COUNT THE NULL VALUES IN SIZE COLUMN
SELECT COUNT(*) FROM TIPS
WHERE SIZE IS NULL;

-- COUNT THE NON NULL VALUE IN TIME COLUMN
SELECT COUNT(*) FROM TIPS
WHERE TIME IS NOT NULL;

-- COUNT THE NON NULL VALUE IN DAY COLUMN
SELECT COUNT(*) FROM TIPS
WHERE DAY IS NOT NULL;

-- COUNT THE NON NULL VALUE IN GENDER COLUMN
SELECT COUNT(*) FROM TIPS
WHERE GENDER IS NOT NULL;

-- COUNT THE NON NULL VALUE IN TOTAL_BILL COLUMN
SELECT COUNT(*) FROM TIPS
WHERE TOTAL_BILL IS NOT NULL;
-- FETCH THE RECORDS

