-- USING GROUP BY
-- COUNT TOTAL RECORDS OF EACH GROUP OF SIZE 
SELECT SIZE,COUNT(*) "TOTAL RECORDS"  FROM TIPS
GROUP BY SIZE; 


-- COUNT TOTAL RECORDS OF SMOKER  GROUP
SELECT SMOKER,COUNT(*) "TOTAL REDCORDS" FROM TIPS
GROUP BY SMOKER; 
 
-- TOTAL BILL OF SMOKER
SELECT SMOKER,SUM(TOTAL_BILL) "TOTAL BILL" FROM TIPS
WHERE SMOKER='YES' 
GROUP BY SMOKER;

-- TOTAL BILLS OF GENDER
SELECT GENDER,SUM(TOTAL_BILL) "TOTAL BILL" FROM TIPS
WHERE GENDER='MALE' OR GENDER='FEMALE' 
GROUP BY GENDER;

-- TOTAL BILLS OF GENDER WITH SIZE 2
SELECT GENDER,SUM(TOTAL_BILL) "TOTAL BILL" FROM TIPS
WHERE GENDER='MALE' OR GENDER='FEMALE' AND SIZE=2 
GROUP BY GENDER;