-- LOGICAL OPERATORS:AND,OR,NOT
-- RETURN ALL RECORDS EITHER BOTH S1_MARKS AND S2_MARKS ARE MORE THAN 90 AND SORT BY S1_MARKS IN DESCENDING ORDER
SELECT * FROM ECE_STUDENTS
WHERE S1_MARKS>90 AND S2_MARKS>90
ORDER BY S1_MARKS DESC;

-- SELECT RECORDS WHERE EITHER S3_MARKS LESS THAN 85 OR PERCENTAGE MORE THAN 85 SORT BY NAME IN ASCENDING ORDER
SELECT * FROM ECE_STUDENTS
WHERE S3_MARKS<85 OR PERCENTAGE>85
ORDER BY NAME ASC;


