use  it_company;

CREATE TABLE EMPLOYEE2(
ID INT auto_increment,
NAME VARCHAR(20) NOT NULL,
GENDER ENUM('MALE','FEMALE') NOT NULL,
DEPT CHAR(20) NOT NULL,
SALARY INT UNSIGNED NOT NULL,
PRIMARY KEY(ID)
);

ALTER TABLE EMPLOYEE2 ADD AGE TINYINT NOT NULL;
describe EMPLOYEE2;
INSERT INTO EMPLOYEE2(NAME,AGE,GENDER,DEPT,SALARY)
VALUES ('AKSHAYA',21,'FEMALE','IT',65000),
('MANOJ',22,'MALE','IT',45000),
('NAVYA',21,'FEMALE','NON-IT',35000),
('SHIVANI',22,'FEMALE','IT',25000),
('AMULYA',20,'FEMALE','SALES',55000),
('PALLAVI',21,'FEMALE','MANAGER',25000),
('RAM',21,'MALE','IT',85000),
('AKSHAY',21,'MALE','SALES',45000),
('NANDHINI',17,'FEMALE','SALES',55000),
('LAXMI',21,'FEMALE','IT',65000)
;

SELECT * FROM EMPLOYEE2;

-- NAME & DEPT 
SELECT NAME,DEPT FROM EMPLOYEE2;

-- ONLY IT DEPT
SELECT * FROM EMPLOYEE2
WHERE DEPT='IT';

-- IT & SALES 
SELECT * FROM EMPLOYEE2
WHERE DEPT='IT' OR DEPT='SALES';

-- SALARY >30000
SELECT * FROM EMPLOYEE2
WHERE SALARY >=30000;

-- UPDATE SALARY RECORDS TO 50000 WHOSE ID=5
UPDATE EMPLOYEE2 SET SALARY=50000
WHERE ID=5;
SELECT * FROM EMPLOYEE2;

-- SELECCT ID,DEPT RECORDS WHERE SAL>30000
SELECT ID,DEPT,SALARY FROM EMPLOYEE2
WHERE SALARY>=30000;

